name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Git, Scons & cmake
      run: |
        sudo apt-get install git scons cmake

    - name: Build & Install json-c
      run: | # XX - Build Static Library & Use That Instead
        cd ..
        git clone https://github.com/json-c/json-c -b json-c-0.16-20220414 json-c
        cd json-c
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=On -DCMAKE_BUILD_TYPE=Release ..
        make
        make install

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./aru
        if-no-files-found: error

  osx-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons & cmake
      run: |
        brew install scons cmake

    - name: Build & Install json-c
      run: | # XX - Build Static Library & Use That Instead
        cd ..
        git clone https://github.com/json-c/json-c -b json-c-0.16-20220414 json-c
        cd json-c
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=On -DCMAKE_BUILD_TYPE=Release ..
        make
        make install

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx-x86_64
        path: ./aru
        if-no-files-found: error
