name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Git, Scons & Cmake
      run: |
        sudo apt-get install git scons cmake

    - name: Build & Install json-c
      run: |
        git clone https://github.com/json-c/json-c -b json-c-0.16-20220414
        cd json-c
        mkdir json-c-build
        cd json-c-build
        cmake ../json-c
        make
        make install

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./aru
        if-no-files-found: error

  osx-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons & json-c
      run: |
        brew install scons json-c

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx-x86_64
        path: ./aru
        if-no-files-found: error
