name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dep
      run: npm install jsonlint -g

    - name: Validate
      run: make validate-json

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Git, Scons, Ncurses
      run: |
        sudo apt-get install git scons libncurses-dev

    - name: Build
      run: make release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./aru
        if-no-files-found: error

  osx-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons & ncurses
      run: |
        sudo brew install scons ncurses

    - name: Build
      run: make release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx-x86_64
        path: ./aru
        if-no-files-found: error
