name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Git, Scons & libtre
      run: |
        sudo apt-get install git scons libtre-dev libtre5

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x86_64
        path: ./aru
        if-no-files-found: error

  osx-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install scons, libtre & autotools
      run: |
        brew install scons tre autoconf automake libtool gettext

    - name: Build and install libtre
      run: |
        cd ..
        git clone https://github.com/laurikari/tre --recursive
        cd tre
        ./utils/autogen.sh
        ./configure
        make
        sudo make install

    - name: Build
      run: make gen-assets release

    - name: Strip
      run: strip ./aru

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: osx-x86_64
        path: ./aru
        if-no-files-found: error
